import "./g.css";
import Footer from "@/components/footer.jsx";
import NavbarComponent from "@/components/navbar";
import { AuthProvider } from "@/context/authContext";
<<<<<<< HEAD
import { LoadingProvider } from "@/context/loading";
import { Toaster, toast } from 'sonner'
=======
>>>>>>> 4755500f58d06b2fabcdb5246c1e3bdff89a35ef

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="mylight">
      <body className="min-h-screen flex flex-col">
        <AuthProvider>
<<<<<<< HEAD
          <LoadingProvider>
            <NavbarComponent />
            <main className="flex-grow pt-[65.9999999px]">{children}</main>
            <footer className="mt-auto">
              <Footer />
            </footer>
          </LoadingProvider>
        </AuthProvider>
        <Toaster position="top-right"
          richColors />
=======
          <NavbarComponent />
          <main className="flex-grow">{children}</main>
          <footer className="mt-auto">
            <Footer />
          </footer>
        </AuthProvider>
>>>>>>> 4755500f58d06b2fabcdb5246c1e3bdff89a35ef
      </body>
    </html>
  );
}
