import "./g.css";
import Footer from "@/components/footer.jsx";
import NavbarComponent from "@/components/navbar";
import { AuthProvider } from "@/context/authContext";
import { LoadingProvider } from "@/context/loading";
import { Toaster, toast } from 'sonner'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="forest">
      <head>
      <link rel="manifest" href="/manifest.json" />
<meta name="theme-color" content="#0d9488" />

      </head>
      <body className="min-h-screen flex flex-col">
        <AuthProvider>
          <LoadingProvider>
            <NavbarComponent />
            <main className="flex-grow pt-[65px] flex justify-center items-center flex-col">{children}</main>
            <footer className="mt-auto">
              <Footer />
            </footer>
          </LoadingProvider>
        </AuthProvider>
        <Toaster position="top-right"
          richColors />
      </body>
    </html>
  );
}
