import "./g.css";
import Footer from "@/components/footer.jsx";
import NavbarComponent from "@/components/navbar";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="mylight">
      <body className="min-h-screen flex flex-col">
        <NavbarComponent />
        <main className="flex-grow">{children}</main>
        <footer className="mt-auto">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
